### ISSUE TITLE
fix D10 incompatibility due to Symfony

### ISSUE THREAD

**Issue by jofranz** [systopia/de.systopia.resourceevent#2]
https://lab.civicrm.org/dev/core/-/issues/2316#note_79953

**Comment by jensschuppe** [comment]
@jofranz Could you elaborate on what needs to be fixed specifically?

**Comment by jofranz** [comment]
Pretty much the same as in:  
https://github.com/systopia/de.systopia.eventmessages/pull/34

_internal reference: 22681_

**Comment by jofranz** [comment]
Wrong extension.
